version: '3'

services:

  front-service:
    environment:
      - AUTH_CONFIG=config.secret.prod.json
    ports:
      - "80:3000"
      - "3001:3001"

  sandbox-service:
    environment:
      - remote_uri=ws://messenger:3000
      - zandbakConfig_workersCount=20
      - zandbakConfig_maxWorkersCoun=40
