version: '3'

services:

  front-service:
    environment:
      - AUTH_CONFIG=config.secret.prod.json
      - ENABLE_GUNSLINGER=false
    ports:
      - "80:3000"
      - "3001:3001"

  sandbox-service:
    environment:
      - remote_uri=ws://messenger:3000
      - zandbakConfig_workersCount=2
      - zandbakConfig_subworkersCount=10
      - LOG_LEVEL=+error,+perf
