version: '3.2'

services:

  front-service:
    environment:
      - AUTH_CONFIG=config.secret.prod.json
      - GUNSLINGERS=false
      - LOG_LEVEL=warn
      - LOG_CONSOLE=false
    ports:
      - "80:3000"
      - "3001:3001"

  sandbox-service:
    environment:
      - remote_uri=ws://messenger:3000
      - zandbakConfig_sand=lodash/subworkers
      - zandbakConfig_backend=electron
      - ELECTRON_ENABLE_LOGGING=1
      - logLevel=+perf,+error,-info
      - zandbakConfig_workersCount=2
      - zandbakConfig_subworkersCount=10
